"""new rules architecture

Revision ID: 0265af996500
Revises: 4f95ecd76bf8
Create Date: 2016-05-24 16:44:53.440494

"""

# revision identifiers, used by Alembic.
revision = '0265af996500'
down_revision = '4f95ecd76bf8'

from alembic import op
import sqlalchemy as sa
import doorman.database
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule', sa.Column('conditions', postgresql.JSONB(), nullable=True))
    op.drop_column('rule', 'action')
    op.drop_column('rule', 'type')
    op.drop_column('rule', 'config')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule', sa.Column('config', postgresql.JSONB(), autoincrement=False, nullable=True))
    op.add_column('rule', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('rule', sa.Column('action', postgresql.ENUM(u'added', u'removed', u'both', name='rule_actions'), autoincrement=False, nullable=False))
    op.drop_column('rule', 'conditions')
    ### end Alembic commands ###
