"""Add version field introduced in osquery v1.7.4.

Revision ID: 14c992522209
Revises: 0bc0a93ac867
Create Date: 2016-05-13 14:31:45.273281

"""

# revision identifiers, used by Alembic.
revision = '14c992522209'
down_revision = '0bc0a93ac867'

from alembic import op
import sqlalchemy as sa
import doorman.database


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status_log', sa.Column('version', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status_log', 'version')
    ### end Alembic commands ###
