"""Add "node_info" column to capture arbitrary node information on the fly

Revision ID: 26139aeff87e
Revises: c17f01adbe31
Create Date: 2016-06-14 23:03:14.838660

"""

# revision identifiers, used by Alembic.
revision = '26139aeff87e'
down_revision = 'c17f01adbe31'

from alembic import op
import sqlalchemy as sa
import doorman.database
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'distributed_query_result', 'distributed_query', ['distributed_query_id'], ['id'])
    op.add_column('node', sa.Column('node_info', postgresql.JSONB(), nullable=True))
    op.drop_index('idx__rule__updated_at', table_name='rule')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx__rule__updated_at', 'rule', ['updated_at'], unique=False)
    op.drop_column('node', 'node_info')
    op.drop_constraint(None, 'distributed_query_result', type_='foreignkey')
    ### end Alembic commands ###
