"""Add "node_info" column to capture arbitrary node information on the fly

Revision ID: 26139aeff87e
Revises: c17f01adbe31
Create Date: 2016-06-14 23:03:14.838660

"""

# revision identifiers, used by Alembic.
revision = '26139aeff87e'
down_revision = 'c17f01adbe31'

from alembic import op
import sqlalchemy as sa
import doorman.database
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('node_info', postgresql.JSONB(), server_default='{}', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node', 'node_info')
    ### end Alembic commands ###
