"""empty message

Revision ID: 32e594f6f771
Revises: a7c48850e100
Create Date: 2016-04-27 14:58:54.626505

"""

# revision identifiers, used by Alembic.
revision = '32e594f6f771'
down_revision = 'a7c48850e100'

from alembic import op
import sqlalchemy as sa
import doorman.database


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('removed', sa.Boolean(), nullable=False, server_default="TRUE"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query', 'removed')
    ### end Alembic commands ###
