"""empty message

Revision ID: 34539eeed672
Revises: b3f73178cee6
Create Date: 2016-04-28 21:59:53.669251

"""

# revision identifiers, used by Alembic.
revision = '34539eeed672'
down_revision = 'b3f73178cee6'

from alembic import op
import sqlalchemy as sa
import doorman.database
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('added', 'removed', 'both', name='rule_actions'), nullable=False),
    sa.Column('alerters', postgresql.ARRAY(String()), nullable=False),
    sa.Column('config', postgresql.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule')
    ### end Alembic commands ###
