"""empty message

Revision ID: 5f646a952b41
Revises: 199c0398a0f6
Create Date: 2016-04-28 18:31:11.076797

"""

# revision identifiers, used by Alembic.
revision = '5f646a952b41'
down_revision = '199c0398a0f6'

from alembic import op
import sqlalchemy as sa
import doorman.database


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    alerters_table = op.create_table('alerter',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('config', doorman.database.JSONBType(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rulealerters',
        sa.Column('rule.id', sa.Integer(), nullable=True),
        sa.Column('alerter.id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['alerter.id'], ['alerter.id'], ),
        sa.ForeignKeyConstraint(['rule.id'], ['rule.id'], )
    )
    ### end Alembic commands ###

    # Insert a default 'debug' alerter
    op.bulk_insert(alerters_table, [
        {'id': 1, 'type': 'debug', 'name': 'Debug Alerter', 'config': None},
    ])


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rulealerters')
    op.drop_table('alerter')
    ### end Alembic commands ###
