"""empty message

Revision ID: a7c48850e100
Revises: 71ef6e2ffb5b
Create Date: 2016-04-25 23:00:36.959573

"""

# revision identifiers, used by Alembic.
revision = 'a7c48850e100'
down_revision = '71ef6e2ffb5b'

from alembic import op
import sqlalchemy as sa
import doorman.database


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distributed_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('sql', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.create_table('distributed_query_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', doorman.database.JSONB(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('distributed_query_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['distributed_query_id'], ['distributed_query.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distributed_query_result')
    op.drop_table('distributed_query')
    ### end Alembic commands ###
