"""empty message

Revision ID: b3f73178cee6
Revises: 32e594f6f771
Create Date: 2016-04-28 13:08:39.663416

"""

# revision identifiers, used by Alembic.
revision = 'b3f73178cee6'
down_revision = '32e594f6f771'

from alembic import op
import sqlalchemy as sa
import doorman.database


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributed_query', sa.Column('not_before', sa.DateTime(), nullable=True))
    op.add_column('distributed_query', sa.Column('retrieved', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distributed_query', 'retrieved')
    op.drop_column('distributed_query', 'not_before')
    ### end Alembic commands ###
