"""Add rule table to configure rules and alerts.

Revision ID: fd28e46e46a6
Revises: d2b00dd93241
Create Date: 2016-05-02 17:46:46.658227

"""

# revision identifiers, used by Alembic.
revision = 'fd28e46e46a6'
down_revision = 'd2b00dd93241'

from alembic import op
import sqlalchemy as sa
import doorman.database
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('added', 'removed', 'both', name='rule_actions'), nullable=False),
    sa.Column('alerters', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('config', postgresql.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule')
    ### end Alembic commands ###
    postgresql.ENUM(name='rule_actions').drop(op.get_bind(), checkfirst=False)
