#!/bin/sh

cd /src/

if [ -z $DOORMAN_ENV ]; then
  export DOORMAN_ENV=prod
fi
export DOORMAN_SETTINGS=$PWD/settings.cfg

exec chpst \
  -u doorman \
  -U doorman \
  gunicorn \
    --workers 4 \
    --bind 0.0.0.0:5000 \
    manage:app
